"""Step 52A: generate downloadable IaC blueprints from persisted topologies."""

from __future__ import annotations

import io
import re
import textwrap
import zipfile
from dataclasses import dataclass
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.models.topology import Topology
from app.services.node_runtime_config import extract_node_runtime_config

CNS_IAC_HEADER = (
    "# Generated by Cloud Networking Studio from your topology blueprint.\n"
    "# Run these files outside CNS in your own environment.\n"
    "# CNS does not execute or apply these files yet.\n"
)

ARCHIVE_ZIP_NAME = "cns-iac-export.zip"
TERRAFORM_ZIP_NAME = "terraform-cns.zip"
ANSIBLE_ZIP_NAME = "ansible-cns.zip"
DOCKER_COMPOSE_FILENAME = "docker-compose.cns.yml"
KUBERNETES_FILENAME = "kubernetes.cns.yaml"


@dataclass(frozen=True)
class ExportNode:
    id: UUID
    name: str
    node_type: str
    image: str | None
    ip_address: str | None
    service_name: str
    runtime: Any
    health_check: dict[str, Any] | None


@dataclass(frozen=True)
class ExportLink:
    id: UUID
    source_name: str
    target_name: str
    network_name: str
    cidr: str | None
    gateway: str | None
    vlan_tag: int | None


@dataclass(frozen=True)
class TopologyExportBundle:
    topology_id: UUID
    topology_name: str
    description: str | None
    runtime_target: str
    networking_mode: str
    nodes: tuple[ExportNode, ...]
    links: tuple[ExportLink, ...]
    networks: tuple[str, ...]


def _safe_service_name(name: str, node_id: UUID) -> str:
    base = re.sub(r"[^a-z0-9_-]+", "-", (name or "node").lower()).strip("-")
    base = re.sub(r"-+", "-", base)[:48]
    if not base:
        base = "node"
    if base[0].isdigit():
        base = f"n-{base}"
    return f"{base}-{str(node_id)[:8]}"


def _yaml_scalar(value: str) -> str:
    if not value:
        return '""'
    if re.fullmatch(r"[a-zA-Z0-9_./:@-]+", value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _indent_block(text: str, spaces: int = 2) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in text.splitlines())


def load_topology_export_bundle(session: Session, topology_id: UUID) -> TopologyExportBundle:
    topo = session.scalar(
        select(Topology)
        .where(Topology.id == topology_id)
        .options(selectinload(Topology.nodes), selectinload(Topology.links))
    )
    if topo is None:
        raise ValueError("topology not found")

    nodes_by_id = {n.id: n for n in topo.nodes}
    export_nodes: list[ExportNode] = []
    for node in topo.nodes:
        runtime = extract_node_runtime_config(node.config)
        export_nodes.append(
            ExportNode(
                id=node.id,
                name=node.name,
                node_type=node.node_type.value if hasattr(node.node_type, "value") else str(node.node_type),
                image=node.image,
                ip_address=node.ip_address,
                service_name=_safe_service_name(node.name, node.id),
                runtime=runtime,
                health_check=runtime.health_check,
            )
        )

    export_links: list[ExportLink] = []
    network_names: set[str] = set()
    for link in topo.links:
        src = nodes_by_id.get(link.source_node_id)
        tgt = nodes_by_id.get(link.target_node_id)
        net = (link.network_name or f"cns-{link.id.hex[:8]}").strip()
        network_names.add(net)
        export_links.append(
            ExportLink(
                id=link.id,
                source_name=src.name if src else str(link.source_node_id),
                target_name=tgt.name if tgt else str(link.target_node_id),
                network_name=net,
                cidr=link.cidr,
                gateway=link.gateway,
                vlan_tag=link.vlan_tag,
            )
        )

    if not network_names:
        network_names.add("cns-network")

    return TopologyExportBundle(
        topology_id=topo.id,
        topology_name=topo.name,
        description=topo.description,
        runtime_target=topo.runtime_target,
        networking_mode=topo.networking_mode,
        nodes=tuple(export_nodes),
        links=tuple(export_links),
        networks=tuple(sorted(network_names)),
    )


def _link_comments(bundle: TopologyExportBundle) -> list[str]:
    lines = ["# Topology links (network segments):"]
    if not bundle.links:
        lines.append("#   (no links — single default network)")
        return lines
    for link in bundle.links:
        parts = [f"{link.source_name} <-> {link.target_name}", f"network={link.network_name}"]
        if link.cidr:
            parts.append(f"cidr={link.cidr}")
        if link.gateway:
            parts.append(f"gateway={link.gateway}")
        if link.vlan_tag is not None:
            parts.append(f"vlan={link.vlan_tag}")
        lines.append(f"#   {' | '.join(parts)}")
    return lines


def generate_docker_compose(bundle: TopologyExportBundle) -> str:
    lines = [
        "# Generated by Cloud Networking Studio from your topology blueprint.",
        "# Run outside CNS in your own environment. CNS does not execute this file yet.",
        f"# Topology: {bundle.topology_name} ({bundle.topology_id})",
        f"# Runtime target: {bundle.runtime_target} | Networking: {bundle.networking_mode}",
        *_link_comments(bundle),
        'version: "3.8"',
        "services:",
    ]
    if not bundle.nodes:
        lines.append("  # TODO: add services — topology has no nodes")
    node_nets = _node_network_map_from_bundle(bundle)
    for node in bundle.nodes:
        lines.append(f"  {node.service_name}:")
        lines.append(f"    # CNS node: {node.name} ({node.node_type})")
        if node.runtime.role_label:
            lines.append(f"    # role_label: {node.runtime.role_label}")
        if node.image:
            lines.append(f"    image: {_yaml_scalar(node.image)}")
        else:
            lines.append("    image: alpine:latest  # TODO: set image from topology")
        if node.runtime.command:
            cmd = " ".join(node.runtime.command)
            lines.append(f"    command: {_yaml_scalar(cmd)}")
        ports = node.runtime.ports or ()
        if ports:
            lines.append("    ports:")
            for p in ports:
                tp = p.target_port or p.port
                lines.append(f'      - "{p.port}:{tp}"  # {p.protocol}')
        if node.runtime.env:
            lines.append("    environment:")
            for k, v in node.runtime.env.items():
                lines.append(f"      {k}: {_yaml_scalar(str(v))}")
        if node.ip_address:
            lines.append(f"    # intent_ip: {node.ip_address}  # TODO: map to compose ipam if needed")
        if node.health_check:
            lines.append(f"    # health_check: {node.health_check}")
        nets = sorted(node_nets.get(node.id, {bundle.networks[0]}))
        lines.append("    networks:")
        for net in nets:
            lines.append(f"      - {_yaml_scalar(net)}")
        lines.append("    restart: unless-stopped")
    lines.append("networks:")
    for net in bundle.networks:
        lines.append(f"  {_yaml_scalar(net)}:")
        lines.append("    driver: bridge")
        link_meta = [lk for lk in bundle.links if lk.network_name == net]
        if link_meta and link_meta[0].cidr:
            lines.append("    # TODO: configure ipam for static CNS intent")
            lines.append(f"    # ipam subnet: {link_meta[0].cidr}")
    lines.append("")
    return "\n".join(lines)


def _node_network_map_from_bundle(bundle: TopologyExportBundle) -> dict[UUID, set[str]]:
    out: dict[UUID, set[str]] = {}
    default = bundle.networks[0] if bundle.networks else "cns-network"
    name_to_id = {n.name: n.id for n in bundle.nodes}
    for link in bundle.links:
        net = link.network_name
        for nm in (link.source_name, link.target_name):
            nid = name_to_id.get(nm)
            if nid:
                out.setdefault(nid, set()).add(net)
    for node in bundle.nodes:
        out.setdefault(node.id, {default})
    return out


def generate_kubernetes_yaml(bundle: TopologyExportBundle) -> str:
    lines = [
        CNS_IAC_HEADER,
        f"# Topology: {bundle.topology_name} ({bundle.topology_id})",
        *_link_comments(bundle),
        "apiVersion: v1",
        "kind: Namespace",
        "metadata:",
        f"  name: cns-{str(bundle.topology_id)[:8]}",
        "  labels:",
        "    app.kubernetes.io/managed-by: cloud-networking-studio",
        f"    cns.topology_id: {bundle.topology_id}",
        "---",
    ]
    if not bundle.nodes:
        lines.append("# TODO: no nodes in topology")
        return "\n".join(lines) + "\n"

    ns = f"cns-{str(bundle.topology_id)[:8]}"
    for node in bundle.nodes:
        lines.extend(
            [
                "apiVersion: apps/v1",
                "kind: Deployment",
                "metadata:",
                f"  name: {node.service_name}",
                f"  namespace: {ns}",
                "  labels:",
                f"    cns.node_name: {_yaml_scalar(node.name)}",
                f"    cns.node_type: {_yaml_scalar(node.node_type)}",
                "spec:",
                "  replicas: 1",
                "  selector:",
                "    matchLabels:",
                f"      app: {node.service_name}",
                "  template:",
                "    metadata:",
                "      labels:",
                f"        app: {node.service_name}",
                "    spec:",
                "      containers:",
                "        - name: workload",
            ]
        )
        if node.image:
            lines.append(f"          image: {_yaml_scalar(node.image)}")
        else:
            lines.append("          image: alpine:latest  # TODO: set image from topology")
        if node.runtime.command:
            lines.append("          command:")
            for part in node.runtime.command:
                lines.append(f"            - {_yaml_scalar(part)}")
        ports = node.runtime.ports or ()
        if ports:
            lines.append("          ports:")
            for p in ports:
                tp = p.target_port or p.port
                lines.append(f"            - containerPort: {tp}  # hostPort TODO: {p.port}")
        if node.runtime.env:
            lines.append("          env:")
            for k, v in node.runtime.env.items():
                lines.append(f"            - name: {k}")
                lines.append(f"              value: {_yaml_scalar(str(v))}")
        if node.health_check:
            lines.append(f"          # health_check: {node.health_check}")
        if node.runtime.kubernetes_service_type:
            lines.append(f"          # kubernetes_service_type: {node.runtime.kubernetes_service_type}")
        lines.append("---")
        if ports:
            lines.extend(
                [
                    "apiVersion: v1",
                    "kind: Service",
                    "metadata:",
                    f"  name: {node.service_name}",
                    f"  namespace: {ns}",
                    "spec:",
                    "  selector:",
                    f"    app: {node.service_name}",
                    "  ports:",
                ]
            )
            for p in ports:
                tp = p.target_port or p.port
                lines.append(f"    - port: {p.port}")
                lines.append(f"      targetPort: {tp}")
                lines.append(f"      protocol: {p.protocol}")
            lines.append("---")
    lines.append("# TODO: NetworkPolicy / multinet segmentation from topology links")
    for link in bundle.links:
        lines.append(
            f"# link {link.source_name} -> {link.target_name} on {link.network_name}"
            + (f" ({link.cidr})" if link.cidr else "")
        )
    lines.append("")
    return "\n".join(lines)


def _terraform_readme(bundle: TopologyExportBundle) -> str:
    return textwrap.dedent(
        f"""\
        # Terraform skeleton — {bundle.topology_name}

        Generated by Cloud Networking Studio from topology `{bundle.topology_id}`.

        - **Do not apply from CNS** — run `terraform plan` / `terraform apply` in your own environment.
        - Review `main.tf` TODOs and wire providers (Docker, Kubernetes, or cloud) to match your target.

        ## Topology summary

        - Runtime target: {bundle.runtime_target}
        - Networking mode: {bundle.networking_mode}
        - Nodes: {len(bundle.nodes)}
        - Links: {len(bundle.links)}
        """
    )


def _terraform_main(bundle: TopologyExportBundle) -> str:
    node_blocks = []
    for node in bundle.nodes:
        img = node.image or "alpine:latest"
        node_blocks.append(
            f"""
# CNS node: {node.name} ({node.node_type})
# TODO: map to docker_container, kubernetes_deployment, or cloud VM
# image = {img!r}
# command = {node.runtime.command!r}
"""
        )
    return (
        f"# Generated from CNS topology: {bundle.topology_name}\n"
        + CNS_IAC_HEADER
        + textwrap.dedent(
            """
            terraform {
              required_version = ">= 1.5.0"
              # TODO: configure backend and provider for your environment
            }

            # Example: Docker provider (uncomment and configure)
            # terraform {
            #   required_providers {
            #     docker = {
            #       source  = "kreuzwerker/docker"
            #       version = "~> 3.0"
            #     }
            #   }
            # }
            """
        )
        + "".join(node_blocks)
        + "\n# TODO: define networks from topology links\n"
    )


def _terraform_variables(bundle: TopologyExportBundle) -> str:
    return textwrap.dedent(
        f"""\
        variable "cns_topology_id" {{
          description = "Cloud Networking Studio topology id"
          type        = string
          default     = "{bundle.topology_id}"
        }}

        variable "cns_topology_name" {{
          description = "Topology display name from CNS"
          type        = string
          default     = "{bundle.topology_name}"
        }}

        variable "runtime_target" {{
          description = "Original CNS runtime target (docker/kubernetes)"
          type        = string
          default     = "{bundle.runtime_target}"
        }}

        # TODO: add variables for images, ports, env per node
        """
    )


def _terraform_outputs(bundle: TopologyExportBundle) -> str:
    lines = [
        "# Outputs — wire after resources are defined",
        'output "cns_topology_id" {',
        "  value = var.cns_topology_id",
        "}",
    ]
    for node in bundle.nodes:
        safe = re.sub(r"[^a-z0-9_]", "_", node.service_name)
        lines.extend(
            [
                f"# output \"{safe}_url\" {{",
                f"#   description = \"Endpoint for CNS node {node.name}\"",
                f"#   value       = \"TODO\"",
                f"# }}",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def _ansible_readme(bundle: TopologyExportBundle) -> str:
    return textwrap.dedent(
        f"""\
        # Ansible skeleton — {bundle.topology_name}

        Generated from CNS topology `{bundle.topology_id}`.

        Run outside CNS:

        ```bash
        ansible-playbook -i inventory.ini playbook.yml
        ```

        CNS does not execute this playbook.
        """
    )


def _ansible_inventory(bundle: TopologyExportBundle) -> str:
    lines = [
        "; Generated by Cloud Networking Studio",
        f"; Topology: {bundle.topology_name} ({bundle.topology_id})",
        "[cns_nodes]",
    ]
    if not bundle.nodes:
        lines.append("; TODO: no nodes")
    for node in bundle.nodes:
        role = node.runtime.role_label or node.node_type
        lines.append(
            f"{node.service_name} cns_node_name={node.name} cns_role={role} "
            f"cns_image={node.image or 'alpine:latest'}"
        )
    lines.extend(
        [
            "",
            "[cns_networks:vars]",
            f"cns_topology_id={bundle.topology_id}",
            f"cns_runtime_target={bundle.runtime_target}",
            "",
        ]
    )
    for link in bundle.links:
        lines.append(
            f"; link {link.source_name}-{link.target_name} network={link.network_name}"
            + (f" cidr={link.cidr}" if link.cidr else "")
        )
    return "\n".join(lines)


def _ansible_playbook(bundle: TopologyExportBundle) -> str:
    task_lines: list[str] = []
    for node in bundle.nodes:
        block = [
            f'    - name: "CNS node {node.name} ({node.service_name})"',
            '      debug:',
            f'        msg: "TODO: provision container/VM for {node.name}"',
            f"      # image: {node.image or 'alpine:latest'}",
            f"      # command: {node.runtime.command!r}",
        ]
        if node.runtime.env:
            block.append("      # environment:")
            for k, v in node.runtime.env.items():
                block.append(f"      #   {k}: {v}")
        if node.runtime.ports:
            for p in node.runtime.ports:
                block.append(
                    f"      # port {p.port}->{p.target_port or p.port} ({p.protocol})"
                )
        task_lines.extend(block)
    if not task_lines:
        task_lines = ['    - debug:', '        msg: "TODO: topology has no nodes"']
    tasks = "\n".join(task_lines)
    return (
        f"---\n"
        f"# Generated from CNS topology: {bundle.topology_name}\n"
        f"# Run outside CNS — not executed by Cloud Networking Studio\n"
        f"- name: CNS topology blueprint ({bundle.topology_id})\n"
        f"  hosts: cns_nodes\n"
        f"  gather_facts: false\n"
        f"  tasks:\n"
        f"{tasks}\n"
    )


def build_terraform_zip(bundle: TopologyExportBundle) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.tf", _terraform_main(bundle))
        zf.writestr("variables.tf", _terraform_variables(bundle))
        zf.writestr("outputs.tf", _terraform_outputs(bundle))
        zf.writestr("README.md", _terraform_readme(bundle))
    return buf.getvalue()


def build_ansible_zip(bundle: TopologyExportBundle) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("inventory.ini", _ansible_inventory(bundle))
        zf.writestr("playbook.yml", _ansible_playbook(bundle))
        zf.writestr("README.md", _ansible_readme(bundle))
    return buf.getvalue()


def build_iac_archive(bundle: TopologyExportBundle) -> bytes:
    buf = io.BytesIO()
    compose = generate_docker_compose(bundle)
    k8s = generate_kubernetes_yaml(bundle)
    tf_zip = build_terraform_zip(bundle)
    ans_zip = build_ansible_zip(bundle)
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(DOCKER_COMPOSE_FILENAME, compose)
        zf.writestr(KUBERNETES_FILENAME, k8s)
        with zipfile.ZipFile(io.BytesIO(tf_zip)) as inner:
            for name in inner.namelist():
                zf.writestr(f"terraform/{name}", inner.read(name))
        with zipfile.ZipFile(io.BytesIO(ans_zip)) as inner:
            for name in inner.namelist():
                zf.writestr(f"ansible/{name}", inner.read(name))
    return buf.getvalue()
